AllCops:
  Exclude:
    - db/schema.rb

Style/Documentation:
  Enabled: false

Layout/HashAlignment:
  Enabled: true
  EnforcedColonStyle: 'table'

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - 'spec/**/*'
