version: "3.8"
services:
  db:
    image: postgres:14
    restart: always
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    command: "postgres -c max_connections=200"
    networks:
      - global

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.4
    container_name: elasticsearch
    env_file: .env
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx2048m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - global
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db
      - elasticsearch
    networks:
      - global

volumes:
  pgdata:
  esdata:

networks:
  global:
