default: &default
  adapter:  postgresql
  encoding: unicode
  host:     <%= ENV["POSTGRES_HOST"] %>
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  port:     <%= ENV["POSTGRES_PORT"] %>
  pool:     <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: es_assignment_development

test:
  <<: *default
  database: es_assignment_development # just so that I don't have to mess with the test database and indexing

production:
  <<: *default
  database: es_assignment_production
