default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  user: user
  password: password
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: es_assignment_development

test:
  <<: *default
  database: es_assignment_test

production:
  <<: *default
  database: es_assignment_production
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
