default: &default
  adapter:  postgresql
  encoding: unicode
  host:     <%= ENV["POSTGRES_HOST"] %>
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  pool:     <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: es_assignment_development

test:
  <<: *default
  database: es_assignment_test

production:
  <<: *default
  database: es_assignment_production
